version: "3.6"

services:
  app:
    build: ./go
    container_name: "gin-app"
    tty: true
    ports:
      - 9998:80
    volumes:
      - ../../:/gin-sample
  db:
    image: "mysql:8.0"
    container_name: "gin-mysql"
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./mysql/my.conf:/etc/mysql/conf.d/docker.cnf
    ports:
      - 3999:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "gin-phpmyadmin"
    ports:
      - 8999:80
    environment:
      PMA_HOST: db
