CREATE DATABASE dev CHARACTER SET utf8;
CREATE DATABASE test_dev CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON dev.* TO 'dev'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test_dev.* TO 'dev'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
